name: substring_highlight
description: Highlight Flutter text at the character-level for customizable and simple search term highlighting.
version: 0.1.1
author: Peter Alvin <github_public@onlyup.com>
homepage: https://github.com/remoteportal/substring_highlight

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: 1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: